from __future__ import annotations
from .analyzer import recover_candidate_stream, recover_data, recover_frame_stream
from .bit_alignment import convert_bits_to_bytes, generate_byte_stream_candidates
from .crc import CRC_PRESETS, CRCParam, compute_crc, evaluate_frame_crc, search_crc_presets
from .fec_decode import decode_hamming_7_4, decode_repetition, encode_convolutional, viterbi_decode
from .framing import detect_frame_boundaries, detect_sequence_continuity, slice_frames
from .integrity import evaluate_multi_frame_integrity
from .line_coding import decode_line_code, evaluate_line_code_hypotheses
from .models import (
    BitHypothesis,
    BitOrder,
    BitPolarity,
    BitStream,
    ByteStreamCandidate,
    CorrectionQuality,
    CRCResult,
    DataQualityLevel,
    DataRecoveryAnalysis,
    DataRecoveryConfig,
    DataRecoveryStatus,
    EpistemicStatus,
    FECCodeFamily,
    FECDecodeResult,
    FECHypothesis,
    FrameBoundary,
    FrameCandidate,
    IntegrityResult,
    LineCodeHypothesis,
    LineCodeType,
    Phase6Handoff,
    PreambleCandidate,
    ReconstructionCandidate,
    ScramblerHypothesis,
    ScramblerType,
)
from .scrambling import berlekamp_massey, descramble_lfsr, evaluate_scrambler_hypotheses, generate_lfsr_sequence
from .synchronization import detect_preamble_candidates, find_pattern_matches

__all__ = [
    "DataRecoveryStatus",
    "DataQualityLevel",
    "EpistemicStatus",
    "BitOrder",
    "BitPolarity",
    "LineCodeType",
    "FECCodeFamily",
    "ScramblerType",
    "BitStream",
    "BitHypothesis",
    "ByteStreamCandidate",
    "PreambleCandidate",
    "FrameBoundary",
    "FrameCandidate",
    "LineCodeHypothesis",
    "ScramblerHypothesis",
    "FECHypothesis",
    "FECDecodeResult",
    "CRCResult",
    "IntegrityResult",
    "CorrectionQuality",
    "ReconstructionCandidate",
    "Phase6Handoff",
    "DataRecoveryConfig",
    "DataRecoveryAnalysis",
    "recover_data",
    "recover_frame_stream",
    "recover_candidate_stream",
    "convert_bits_to_bytes",
    "generate_byte_stream_candidates",
    "detect_preamble_candidates",
    "find_pattern_matches",
    "detect_frame_boundaries",
    "slice_frames",
    "detect_sequence_continuity",
    "decode_line_code",
    "evaluate_line_code_hypotheses",
    "berlekamp_massey",
    "generate_lfsr_sequence",
    "descramble_lfsr",
    "evaluate_scrambler_hypotheses",
    "compute_crc",
    "evaluate_frame_crc",
    "search_crc_presets",
    "evaluate_multi_frame_integrity",
    "encode_convolutional",
    "viterbi_decode",
    "decode_hamming_7_4",
    "decode_repetition",
]
