function(sih_probe_config_dependency display_name package_name)
    find_package(${package_name} CONFIG QUIET)
    if(${package_name}_FOUND)
        message(STATUS "Native dependency probe: ${display_name} found")
    else()
        message(STATUS "Native dependency probe: ${display_name} not found (using the portable baseline where available)")
    endif()
endfunction()

function(sih_probe_future_dependencies)
    sih_probe_config_dependency("FFTW3" FFTW3)
    sih_probe_config_dependency("libsndfile" SndFile)
    sih_probe_config_dependency("AFF3CT" AFF3CT)
endfunction()
